### ISSUE TITLE
Use IsValueType

### ISSUE THREAD

**Issue by joacar** [joacar/BindablePicker#3]
The method `IsPrimitive` is bad since it doesn't handle all types. Change to `item.GetType().GetTypeInfo().IsValueType` instead to handle - thats right - all value types

**Comment by Mr-Pearce** [comment]
No Two way Binding Support? If i Bind the Selected Property to my Viewmodel it don#t changes it from the ViewModel

**Comment by joacar** [comment]
@Mr-Pearce

The `SelectedItem` property supports TwoWay-binding. Please make sure 1) the page has the correct view model as `BindingContext` 2) the view model property raises the `INotifyPropertyChanged` event

Off-topic
 Please open a new issue if you have questions or found a bug. Thanks :)
